import type { P7Poi } from "./rank.js";

export const p7PoiCorpus = [
  {
    "poi_id": "C001",
    "poi_name": "The Workshop Coffee",
    "brand": "The Workshop",
    "category": "Quán cà phê",
    "sub_category": "Specialty Coffee",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "27 Ngô Đức Kế, Quận 1",
    "latitude": 10.7738,
    "longitude": 106.704,
    "rating": 4.6,
    "review_count": 1560,
    "popularity_score": 91.0,
    "price_level": 3,
    "opening_hours": "07:00-22:30",
    "attributes": [
      "wifi",
      "yên tĩnh",
      "phù hợp làm việc",
      "ổ cắm",
      "điều hòa"
    ],
    "tags": [
      "work-friendly",
      "quiet",
      "coffee",
      "meeting"
    ],
    "description": "Quán cà phê specialty có không gian yên tĩnh, nhiều ổ cắm và phù hợp làm việc.",
    "source_row": 2,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "C002",
    "poi_name": "Highlands Coffee Nguyễn Huệ",
    "brand": "Highlands Coffee",
    "category": "Quán cà phê",
    "sub_category": "Coffee Chain",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "68 Nguyễn Huệ, Quận 1",
    "latitude": 10.7752,
    "longitude": 106.7035,
    "rating": 4.2,
    "review_count": 2110,
    "popularity_score": 88.0,
    "price_level": 2,
    "opening_hours": "07:00-23:00",
    "attributes": [
      "wifi",
      "phù hợp gặp bạn",
      "đông khách",
      "gần phố đi bộ"
    ],
    "tags": [
      "brand",
      "coffee",
      "central"
    ],
    "description": "Chi nhánh Highlands Coffee tại trung tâm Quận 1, thuận tiện gặp mặt và nghỉ chân.",
    "source_row": 3,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "C003",
    "poi_name": "Cộng Cà Phê Hồ Gươm",
    "brand": "Cộng Cà Phê",
    "category": "Quán cà phê",
    "sub_category": "Coffee Chain",
    "city": "Hà Nội",
    "district": "Hoàn Kiếm",
    "address": "116 Cầu Gỗ, Hoàn Kiếm",
    "latitude": 21.032,
    "longitude": 105.8529,
    "rating": 4.4,
    "review_count": 1840,
    "popularity_score": 87.0,
    "price_level": 2,
    "opening_hours": "07:30-23:00",
    "attributes": [
      "view đẹp",
      "gần hồ",
      "phù hợp du lịch",
      "đông khách"
    ],
    "tags": [
      "coffee",
      "lake-view",
      "tourist"
    ],
    "description": "Quán cà phê phong cách hoài cổ gần Hồ Gươm, phù hợp du khách và chụp ảnh.",
    "source_row": 4,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "C004",
    "poi_name": "Tranquil Books & Coffee",
    "brand": "Tranquil",
    "category": "Quán cà phê",
    "sub_category": "Book Cafe",
    "city": "Hà Nội",
    "district": "Hoàn Kiếm",
    "address": "5 Nguyễn Quang Bích, Hoàn Kiếm",
    "latitude": 21.0328,
    "longitude": 105.8458,
    "rating": 4.7,
    "review_count": 940,
    "popularity_score": 85.0,
    "price_level": 2,
    "opening_hours": "08:00-22:30",
    "attributes": [
      "yên tĩnh",
      "wifi",
      "sách",
      "phù hợp học tập",
      "phù hợp làm việc"
    ],
    "tags": [
      "quiet",
      "study",
      "book-cafe"
    ],
    "description": "Quán cà phê sách yên tĩnh, phù hợp học bài, đọc sách và làm việc cá nhân.",
    "source_row": 5,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "C005",
    "poi_name": "Dream Beans Coffee Đà Nẵng",
    "brand": "Dream Beans",
    "category": "Quán cà phê",
    "sub_category": "Specialty Coffee",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "15 Trần Phú, Hải Châu",
    "latitude": 16.071,
    "longitude": 108.223,
    "rating": 4.5,
    "review_count": 620,
    "popularity_score": 78.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "wifi",
      "yên tĩnh",
      "gần sông",
      "phù hợp làm việc"
    ],
    "tags": [
      "coffee",
      "work-friendly",
      "river"
    ],
    "description": "Quán cà phê có không gian yên tĩnh, gần sông Hàn, phù hợp làm việc.",
    "source_row": 6,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "C006",
    "poi_name": "Dalat View Coffee",
    "brand": "Dalat View",
    "category": "Quán cà phê",
    "sub_category": "View Cafe",
    "city": "Đà Lạt",
    "district": "Phường 3",
    "address": "49 Khe Sanh, Đà Lạt",
    "latitude": 11.9301,
    "longitude": 108.4602,
    "rating": 4.4,
    "review_count": 1330,
    "popularity_score": 84.0,
    "price_level": 2,
    "opening_hours": "06:30-22:00",
    "attributes": [
      "view đẹp",
      "check-in",
      "ngoài trời",
      "phù hợp cặp đôi"
    ],
    "tags": [
      "view",
      "check-in",
      "romantic"
    ],
    "description": "Quán cà phê có view thung lũng, phù hợp chụp ảnh và hẹn hò.",
    "source_row": 7,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "C007",
    "poi_name": "WorkHub Cafe Cầu Giấy",
    "brand": "WorkHub",
    "category": "Quán cà phê",
    "sub_category": "Work Cafe",
    "city": "Hà Nội",
    "district": "Cầu Giấy",
    "address": "89 Duy Tân, Cầu Giấy",
    "latitude": 21.0304,
    "longitude": 105.7871,
    "rating": 4.5,
    "review_count": 480,
    "popularity_score": 76.0,
    "price_level": 2,
    "opening_hours": "07:00-23:00",
    "attributes": [
      "wifi mạnh",
      "yên tĩnh",
      "phòng họp",
      "ổ cắm",
      "bãi đỗ xe"
    ],
    "tags": [
      "work-friendly",
      "meeting",
      "parking"
    ],
    "description": "Quán cà phê thiết kế cho làm việc và họp nhóm, có phòng họp nhỏ và bãi đỗ xe.",
    "source_row": 8,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "C008",
    "poi_name": "Mộc Cafe Thủ Đức",
    "brand": "Mộc Cafe",
    "category": "Quán cà phê",
    "sub_category": "Garden Cafe",
    "city": "TP.HCM",
    "district": "Thủ Đức",
    "address": "23 Võ Văn Ngân, Thủ Đức",
    "latitude": 10.8491,
    "longitude": 106.7724,
    "rating": 4.1,
    "review_count": 350,
    "popularity_score": 64.0,
    "price_level": 1,
    "opening_hours": "06:30-22:00",
    "attributes": [
      "sân vườn",
      "giá rẻ",
      "phù hợp nhóm",
      "bãi đỗ xe"
    ],
    "tags": [
      "garden",
      "budget",
      "parking"
    ],
    "description": "Quán cà phê sân vườn giá hợp lý, phù hợp đi nhóm và có chỗ gửi xe.",
    "source_row": 9,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R001",
    "poi_name": "Nhà hàng Ngon 138",
    "brand": "Ngon",
    "category": "Nhà hàng",
    "sub_category": "Vietnamese Restaurant",
    "city": "Hà Nội",
    "district": "Hoàn Kiếm",
    "address": "138 Trần Hưng Đạo, Hoàn Kiếm",
    "latitude": 21.022,
    "longitude": 105.848,
    "rating": 4.3,
    "review_count": 1820,
    "popularity_score": 86.0,
    "price_level": 3,
    "opening_hours": "10:00-22:00",
    "attributes": [
      "phù hợp gia đình",
      "món Việt",
      "không gian rộng",
      "đặt bàn"
    ],
    "tags": [
      "family",
      "vietnamese",
      "group"
    ],
    "description": "Nhà hàng món Việt có không gian rộng, phù hợp gia đình và nhóm khách du lịch.",
    "source_row": 10,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R002",
    "poi_name": "Pizza 4P's Lê Thánh Tôn",
    "brand": "Pizza 4P's",
    "category": "Nhà hàng",
    "sub_category": "Italian Restaurant",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "8 Lê Thánh Tôn, Quận 1",
    "latitude": 10.7789,
    "longitude": 106.7048,
    "rating": 4.7,
    "review_count": 4210,
    "popularity_score": 96.0,
    "price_level": 4,
    "opening_hours": "10:00-23:00",
    "attributes": [
      "lãng mạn",
      "phù hợp hẹn hò",
      "đặt bàn",
      "món Ý"
    ],
    "tags": [
      "romantic",
      "date",
      "italian"
    ],
    "description": "Nhà hàng Ý nổi tiếng, không gian đẹp và phù hợp hẹn hò hoặc dịp đặc biệt.",
    "source_row": 11,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R003",
    "poi_name": "Bún Chả Hương Liên",
    "brand": "Hương Liên",
    "category": "Nhà hàng",
    "sub_category": "Bún Chả",
    "city": "Hà Nội",
    "district": "Hai Bà Trưng",
    "address": "24 Lê Văn Hưu, Hai Bà Trưng",
    "latitude": 21.018,
    "longitude": 105.854,
    "rating": 4.2,
    "review_count": 3220,
    "popularity_score": 90.0,
    "price_level": 2,
    "opening_hours": "08:00-21:00",
    "attributes": [
      "món địa phương",
      "du lịch",
      "giá vừa phải",
      "đông khách"
    ],
    "tags": [
      "local-food",
      "tourist",
      "bun-cha"
    ],
    "description": "Quán bún chả nổi tiếng ở Hà Nội, phù hợp du khách muốn thử món địa phương.",
    "source_row": 12,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R004",
    "poi_name": "Phở Thìn Lò Đúc",
    "brand": "Phở Thìn",
    "category": "Nhà hàng",
    "sub_category": "Phở",
    "city": "Hà Nội",
    "district": "Hai Bà Trưng",
    "address": "13 Lò Đúc, Hai Bà Trưng",
    "latitude": 21.0172,
    "longitude": 105.8624,
    "rating": 4.1,
    "review_count": 2760,
    "popularity_score": 85.0,
    "price_level": 2,
    "opening_hours": "06:00-21:30",
    "attributes": [
      "phở bò",
      "món địa phương",
      "ăn nhanh",
      "đông khách"
    ],
    "tags": [
      "pho",
      "local-food",
      "quick"
    ],
    "description": "Quán phở bò nổi tiếng, phù hợp ăn nhanh và trải nghiệm ẩm thực Hà Nội.",
    "source_row": 13,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R005",
    "poi_name": "Bếp Nhà Đà Nẵng",
    "brand": "Bếp Nhà",
    "category": "Nhà hàng",
    "sub_category": "Vietnamese Restaurant",
    "city": "Đà Nẵng",
    "district": "Sơn Trà",
    "address": "102 Võ Nguyên Giáp, Sơn Trà",
    "latitude": 16.0603,
    "longitude": 108.2457,
    "rating": 4.5,
    "review_count": 980,
    "popularity_score": 82.0,
    "price_level": 3,
    "opening_hours": "10:00-23:00",
    "attributes": [
      "gần biển",
      "phù hợp gia đình",
      "món Việt",
      "hải sản"
    ],
    "tags": [
      "family",
      "seafood",
      "beach"
    ],
    "description": "Nhà hàng gần biển phục vụ món Việt và hải sản, phù hợp gia đình có trẻ em.",
    "source_row": 14,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R006",
    "poi_name": "Quán Ăn Đêm 24h Nguyễn Trãi",
    "brand": "Ăn Đêm 24h",
    "category": "Nhà hàng",
    "sub_category": "Late Night Food",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "120 Nguyễn Trãi, Quận 1",
    "latitude": 10.7662,
    "longitude": 106.691,
    "rating": 4.0,
    "review_count": 720,
    "popularity_score": 70.0,
    "price_level": 1,
    "opening_hours": "18:00-03:00",
    "attributes": [
      "mở khuya",
      "giá rẻ",
      "ăn nhanh",
      "phù hợp nhóm"
    ],
    "tags": [
      "late-night",
      "budget",
      "street-food"
    ],
    "description": "Quán ăn mở khuya với nhiều món nhanh, phù hợp ăn đêm và đi nhóm.",
    "source_row": 15,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R007",
    "poi_name": "Chay An Lạc",
    "brand": "An Lạc",
    "category": "Nhà hàng",
    "sub_category": "Vegetarian Restaurant",
    "city": "TP.HCM",
    "district": "Quận 3",
    "address": "45 Võ Văn Tần, Quận 3",
    "latitude": 10.778,
    "longitude": 106.6905,
    "rating": 4.4,
    "review_count": 860,
    "popularity_score": 75.0,
    "price_level": 2,
    "opening_hours": "09:00-21:30",
    "attributes": [
      "món chay",
      "yên tĩnh",
      "tốt cho sức khỏe",
      "phù hợp gia đình"
    ],
    "tags": [
      "vegetarian",
      "healthy",
      "family"
    ],
    "description": "Nhà hàng chay có không gian yên tĩnh, phù hợp gia đình và người ăn lành mạnh.",
    "source_row": 16,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R008",
    "poi_name": "Rooftop Sky Garden",
    "brand": "Sky Garden",
    "category": "Nhà hàng",
    "sub_category": "Rooftop Bar",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "12 Nguyễn Huệ, Quận 1",
    "latitude": 10.775,
    "longitude": 106.7042,
    "rating": 4.6,
    "review_count": 1220,
    "popularity_score": 88.0,
    "price_level": 4,
    "opening_hours": "17:00-01:00",
    "attributes": [
      "rooftop",
      "lãng mạn",
      "view đẹp",
      "cocktail",
      "hẹn hò"
    ],
    "tags": [
      "rooftop",
      "romantic",
      "night-view"
    ],
    "description": "Rooftop có view trung tâm, phù hợp hẹn hò, gặp bạn và trải nghiệm buổi tối.",
    "source_row": 17,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R009",
    "poi_name": "Lẩu Gà Lá É Tao Ngộ",
    "brand": "Tao Ngộ",
    "category": "Nhà hàng",
    "sub_category": "Hotpot",
    "city": "Đà Lạt",
    "district": "Phường 8",
    "address": "5 Đường 3 Tháng 4, Đà Lạt",
    "latitude": 11.935,
    "longitude": 108.4421,
    "rating": 4.3,
    "review_count": 2120,
    "popularity_score": 84.0,
    "price_level": 2,
    "opening_hours": "10:00-22:00",
    "attributes": [
      "món địa phương",
      "phù hợp nhóm",
      "ấm cúng"
    ],
    "tags": [
      "local-food",
      "group",
      "hotpot"
    ],
    "description": "Quán lẩu gà lá é nổi tiếng, phù hợp đi nhóm khi du lịch Đà Lạt.",
    "source_row": 18,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "R010",
    "poi_name": "Nhà hàng Gia Đình Hoa Sen",
    "brand": "Hoa Sen",
    "category": "Nhà hàng",
    "sub_category": "Family Restaurant",
    "city": "Hà Nội",
    "district": "Tây Hồ",
    "address": "88 Xuân Diệu, Tây Hồ",
    "latitude": 21.0624,
    "longitude": 105.8226,
    "rating": 4.2,
    "review_count": 510,
    "popularity_score": 72.0,
    "price_level": 2,
    "opening_hours": "10:00-22:00",
    "attributes": [
      "phù hợp trẻ em",
      "ghế trẻ em",
      "bãi đỗ xe",
      "không gian rộng"
    ],
    "tags": [
      "family",
      "kids",
      "parking"
    ],
    "description": "Nhà hàng gia đình có ghế trẻ em và bãi đỗ xe, phù hợp gia đình có con nhỏ.",
    "source_row": 19,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "H001",
    "poi_name": "Sea Pearl Hotel Đà Nẵng",
    "brand": "Sea Pearl",
    "category": "Khách sạn",
    "sub_category": "Beach Hotel",
    "city": "Đà Nẵng",
    "district": "Sơn Trà",
    "address": "18 Võ Nguyên Giáp, Sơn Trà",
    "latitude": 16.066,
    "longitude": 108.2468,
    "rating": 4.4,
    "review_count": 920,
    "popularity_score": 80.0,
    "price_level": 3,
    "opening_hours": "24/7",
    "attributes": [
      "gần biển",
      "hồ bơi",
      "bữa sáng",
      "phù hợp gia đình"
    ],
    "tags": [
      "hotel",
      "beach",
      "pool",
      "family"
    ],
    "description": "Khách sạn gần biển Mỹ Khê, có hồ bơi, bữa sáng và phù hợp gia đình.",
    "source_row": 20,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "H002",
    "poi_name": "Ocean View Resort Đà Nẵng",
    "brand": "Ocean View",
    "category": "Khách sạn",
    "sub_category": "Resort",
    "city": "Đà Nẵng",
    "district": "Ngũ Hành Sơn",
    "address": "120 Trường Sa, Ngũ Hành Sơn",
    "latitude": 16.0115,
    "longitude": 108.264,
    "rating": 4.6,
    "review_count": 760,
    "popularity_score": 83.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "gần biển",
      "resort",
      "hồ bơi",
      "spa",
      "phù hợp cặp đôi"
    ],
    "tags": [
      "resort",
      "beach",
      "luxury",
      "romantic"
    ],
    "description": "Resort gần biển, có spa và hồ bơi, phù hợp nghỉ dưỡng và cặp đôi.",
    "source_row": 21,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "H003",
    "poi_name": "Hanoi Business Hotel",
    "brand": "Hanoi Business",
    "category": "Khách sạn",
    "sub_category": "Business Hotel",
    "city": "Hà Nội",
    "district": "Cầu Giấy",
    "address": "22 Duy Tân, Cầu Giấy",
    "latitude": 21.03,
    "longitude": 105.785,
    "rating": 4.2,
    "review_count": 610,
    "popularity_score": 70.0,
    "price_level": 3,
    "opening_hours": "24/7",
    "attributes": [
      "gần văn phòng",
      "wifi mạnh",
      "phòng họp",
      "phù hợp công tác"
    ],
    "tags": [
      "business",
      "meeting",
      "wifi"
    ],
    "description": "Khách sạn phù hợp đi công tác tại khu văn phòng Cầu Giấy.",
    "source_row": 22,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "H004",
    "poi_name": "Dalat Garden Homestay",
    "brand": "Dalat Garden",
    "category": "Khách sạn",
    "sub_category": "Homestay",
    "city": "Đà Lạt",
    "district": "Phường 4",
    "address": "32 Hoàng Diệu, Đà Lạt",
    "latitude": 11.946,
    "longitude": 108.433,
    "rating": 4.5,
    "review_count": 680,
    "popularity_score": 78.0,
    "price_level": 2,
    "opening_hours": "07:00-23:00",
    "attributes": [
      "sân vườn",
      "check-in",
      "giá hợp lý",
      "phù hợp nhóm"
    ],
    "tags": [
      "homestay",
      "check-in",
      "budget"
    ],
    "description": "Homestay có sân vườn, phù hợp nhóm bạn và chụp ảnh.",
    "source_row": 23,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "H005",
    "poi_name": "Saigon Central Hotel",
    "brand": "Saigon Central",
    "category": "Khách sạn",
    "sub_category": "City Hotel",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "99 Lý Tự Trọng, Quận 1",
    "latitude": 10.7763,
    "longitude": 106.6985,
    "rating": 4.1,
    "review_count": 870,
    "popularity_score": 76.0,
    "price_level": 3,
    "opening_hours": "24/7",
    "attributes": [
      "trung tâm",
      "gần chợ",
      "phù hợp du lịch",
      "đi bộ"
    ],
    "tags": [
      "central",
      "tourist",
      "market"
    ],
    "description": "Khách sạn trung tâm Quận 1, thuận tiện tham quan và mua sắm.",
    "source_row": 24,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "A001",
    "poi_name": "Thảo Cầm Viên Sài Gòn",
    "brand": "Thảo Cầm Viên",
    "category": "Điểm tham quan",
    "sub_category": "Zoo",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "2 Nguyễn Bỉnh Khiêm, Quận 1",
    "latitude": 10.7877,
    "longitude": 106.7054,
    "rating": 4.3,
    "review_count": 6400,
    "popularity_score": 92.0,
    "price_level": 2,
    "opening_hours": "07:00-17:30",
    "attributes": [
      "phù hợp trẻ em",
      "ngoài trời",
      "gia đình",
      "giá rẻ"
    ],
    "tags": [
      "kids",
      "family",
      "outdoor"
    ],
    "description": "Điểm tham quan phù hợp gia đình và trẻ em với nhiều khu vực ngoài trời.",
    "source_row": 25,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "A002",
    "poi_name": "Công viên Thống Nhất",
    "brand": "Công viên Thống Nhất",
    "category": "Công viên",
    "sub_category": "Park",
    "city": "Hà Nội",
    "district": "Hai Bà Trưng",
    "address": "Trần Nhân Tông, Hai Bà Trưng",
    "latitude": 21.017,
    "longitude": 105.843,
    "rating": 4.2,
    "review_count": 2100,
    "popularity_score": 76.0,
    "price_level": 1,
    "opening_hours": "05:00-22:00",
    "attributes": [
      "ngoài trời",
      "đi dạo",
      "phù hợp trẻ em",
      "thể thao"
    ],
    "tags": [
      "park",
      "kids",
      "walking"
    ],
    "description": "Công viên lớn ở Hà Nội, phù hợp đi dạo, tập thể dục và đưa trẻ em vui chơi.",
    "source_row": 26,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "A003",
    "poi_name": "Cầu Vàng Bà Nà Hills",
    "brand": "Sun World",
    "category": "Điểm tham quan",
    "sub_category": "Theme Park",
    "city": "Đà Nẵng",
    "district": "Hòa Vang",
    "address": "Bà Nà Hills, Hòa Vang",
    "latitude": 16.0017,
    "longitude": 107.9974,
    "rating": 4.6,
    "review_count": 15800,
    "popularity_score": 98.0,
    "price_level": 4,
    "opening_hours": "08:00-17:00",
    "attributes": [
      "check-in",
      "du lịch",
      "gia đình",
      "view đẹp"
    ],
    "tags": [
      "check-in",
      "tourist",
      "family"
    ],
    "description": "Điểm check-in nổi tiếng với Cầu Vàng và khu du lịch Bà Nà Hills.",
    "source_row": 27,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "A004",
    "poi_name": "Quảng trường Lâm Viên",
    "brand": "Quảng trường Lâm Viên",
    "category": "Điểm tham quan",
    "sub_category": "Square",
    "city": "Đà Lạt",
    "district": "Phường 1",
    "address": "Trần Quốc Toản, Đà Lạt",
    "latitude": 11.94,
    "longitude": 108.444,
    "rating": 4.4,
    "review_count": 8900,
    "popularity_score": 90.0,
    "price_level": 1,
    "opening_hours": "24/7",
    "attributes": [
      "check-in",
      "miễn phí",
      "gần hồ",
      "du lịch"
    ],
    "tags": [
      "check-in",
      "free",
      "tourist"
    ],
    "description": "Địa điểm check-in nổi tiếng ở Đà Lạt, gần hồ Xuân Hương.",
    "source_row": 28,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "A005",
    "poi_name": "Lotte Center Hà Nội",
    "brand": "Lotte Center",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Hà Nội",
    "district": "Ba Đình",
    "address": "54 Liễu Giai, Ba Đình",
    "latitude": 21.032,
    "longitude": 105.812,
    "rating": 4.5,
    "review_count": 5200,
    "popularity_score": 91.0,
    "price_level": 3,
    "opening_hours": "09:30-22:00",
    "attributes": [
      "mua sắm",
      "ăn uống",
      "đài quan sát",
      "bãi đỗ xe"
    ],
    "tags": [
      "mall",
      "shopping",
      "view",
      "parking"
    ],
    "description": "Trung tâm thương mại có nhiều nhà hàng, mua sắm và đài quan sát.",
    "source_row": 29,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "S001",
    "poi_name": "ATM Vietcombank Nguyễn Huệ",
    "brand": "Vietcombank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "65 Nguyễn Huệ, Quận 1",
    "latitude": 10.7755,
    "longitude": 106.7034,
    "rating": 4.0,
    "review_count": 180,
    "popularity_score": 68.0,
    "price_level": 1,
    "opening_hours": "24/7",
    "attributes": [
      "rút tiền",
      "24/7",
      "gần phố đi bộ"
    ],
    "tags": [
      "atm",
      "bank",
      "24h"
    ],
    "description": "ATM Vietcombank hoạt động 24/7 gần phố đi bộ Nguyễn Huệ.",
    "source_row": 30,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "S002",
    "poi_name": "ATM Techcombank Hồ Gươm",
    "brand": "Techcombank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Hà Nội",
    "district": "Hoàn Kiếm",
    "address": "10 Đinh Tiên Hoàng, Hoàn Kiếm",
    "latitude": 21.0315,
    "longitude": 105.8522,
    "rating": 4.0,
    "review_count": 150,
    "popularity_score": 66.0,
    "price_level": 1,
    "opening_hours": "24/7",
    "attributes": [
      "rút tiền",
      "24/7",
      "gần hồ"
    ],
    "tags": [
      "atm",
      "bank",
      "24h"
    ],
    "description": "ATM Techcombank gần Hồ Gươm, thuận tiện cho du khách.",
    "source_row": 31,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "S003",
    "poi_name": "Trạm xăng Petrolimex Cầu Giấy",
    "brand": "Petrolimex",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Hà Nội",
    "district": "Cầu Giấy",
    "address": "98 Xuân Thủy, Cầu Giấy",
    "latitude": 21.037,
    "longitude": 105.782,
    "rating": 4.1,
    "review_count": 310,
    "popularity_score": 72.0,
    "price_level": 1,
    "opening_hours": "24/7",
    "attributes": [
      "xăng dầu",
      "24/7",
      "toilet",
      "bơm lốp"
    ],
    "tags": [
      "fuel",
      "24h",
      "toilet"
    ],
    "description": "Trạm xăng Petrolimex hoạt động 24/7 có toilet và bơm lốp.",
    "source_row": 32,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "S004",
    "poi_name": "Trạm sạc EV One Đà Nẵng",
    "brand": "EV One",
    "category": "Trạm sạc điện",
    "sub_category": "EV Charging",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "2 Bạch Đằng, Hải Châu",
    "latitude": 16.0715,
    "longitude": 108.224,
    "rating": 4.3,
    "review_count": 120,
    "popularity_score": 65.0,
    "price_level": 2,
    "opening_hours": "06:00-23:00",
    "attributes": [
      "sạc nhanh",
      "gần trung tâm",
      "bãi đỗ xe"
    ],
    "tags": [
      "ev",
      "charging",
      "parking"
    ],
    "description": "Trạm sạc điện có sạc nhanh và chỗ đỗ xe gần trung tâm Đà Nẵng.",
    "source_row": 33,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "S005",
    "poi_name": "Bệnh viện Bạch Mai",
    "brand": "Bạch Mai",
    "category": "Bệnh viện",
    "sub_category": "Hospital",
    "city": "Hà Nội",
    "district": "Đống Đa",
    "address": "78 Giải Phóng, Đống Đa",
    "latitude": 21.0007,
    "longitude": 105.8411,
    "rating": 4.0,
    "review_count": 5800,
    "popularity_score": 93.0,
    "price_level": 2,
    "opening_hours": "24/7",
    "attributes": [
      "cấp cứu",
      "đa khoa",
      "24/7"
    ],
    "tags": [
      "hospital",
      "emergency",
      "24h"
    ],
    "description": "Bệnh viện đa khoa lớn tại Hà Nội, có cấp cứu 24/7.",
    "source_row": 34,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "S006",
    "poi_name": "Bệnh viện Vinmec Central Park",
    "brand": "Vinmec",
    "category": "Bệnh viện",
    "sub_category": "Hospital",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "208 Nguyễn Hữu Cảnh, Bình Thạnh",
    "latitude": 10.7944,
    "longitude": 106.7218,
    "rating": 4.4,
    "review_count": 2100,
    "popularity_score": 88.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "quốc tế",
      "cấp cứu",
      "dịch vụ tốt",
      "24/7"
    ],
    "tags": [
      "hospital",
      "premium",
      "emergency"
    ],
    "description": "Bệnh viện quốc tế có dịch vụ cao cấp và cấp cứu 24/7.",
    "source_row": 35,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "S007",
    "poi_name": "Nhà thuốc Pharmacity Nguyễn Trãi",
    "brand": "Pharmacity",
    "category": "Nhà thuốc",
    "sub_category": "Pharmacy",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "82 Nguyễn Trãi, Quận 1",
    "latitude": 10.7673,
    "longitude": 106.6914,
    "rating": 4.1,
    "review_count": 220,
    "popularity_score": 68.0,
    "price_level": 1,
    "opening_hours": "07:00-23:00",
    "attributes": [
      "thuốc",
      "chăm sóc sức khỏe",
      "mở muộn"
    ],
    "tags": [
      "pharmacy",
      "health"
    ],
    "description": "Nhà thuốc gần trung tâm, mở cửa đến khuya.",
    "source_row": 36,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "M001",
    "poi_name": "Vincom Center Đồng Khởi",
    "brand": "Vincom",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "72 Lê Thánh Tôn, Quận 1",
    "latitude": 10.778,
    "longitude": 106.7017,
    "rating": 4.5,
    "review_count": 7200,
    "popularity_score": 94.0,
    "price_level": 3,
    "opening_hours": "09:30-22:00",
    "attributes": [
      "mua sắm",
      "ăn uống",
      "giải trí",
      "trung tâm"
    ],
    "tags": [
      "mall",
      "shopping",
      "food",
      "central"
    ],
    "description": "Trung tâm thương mại lớn ở Quận 1 với nhiều thương hiệu, nhà hàng và giải trí.",
    "source_row": 37,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "M002",
    "poi_name": "Vincom Nguyễn Chí Thanh",
    "brand": "Vincom",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Hà Nội",
    "district": "Đống Đa",
    "address": "54A Nguyễn Chí Thanh, Đống Đa",
    "latitude": 21.0238,
    "longitude": 105.809,
    "rating": 4.4,
    "review_count": 4600,
    "popularity_score": 89.0,
    "price_level": 3,
    "opening_hours": "09:30-22:00",
    "attributes": [
      "mua sắm",
      "ăn uống",
      "rạp phim",
      "bãi đỗ xe"
    ],
    "tags": [
      "mall",
      "cinema",
      "shopping"
    ],
    "description": "Trung tâm thương mại có rạp phim, nhà hàng và bãi đỗ xe.",
    "source_row": 38,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "M003",
    "poi_name": "Galaxy Cinema Nguyễn Du",
    "brand": "Galaxy Cinema",
    "category": "Rạp phim",
    "sub_category": "Cinema",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "116 Nguyễn Du, Quận 1",
    "latitude": 10.7733,
    "longitude": 106.6922,
    "rating": 4.2,
    "review_count": 2800,
    "popularity_score": 83.0,
    "price_level": 2,
    "opening_hours": "09:00-23:30",
    "attributes": [
      "rạp phim",
      "giải trí",
      "trung tâm"
    ],
    "tags": [
      "cinema",
      "entertainment"
    ],
    "description": "Rạp chiếu phim Galaxy tại trung tâm Quận 1.",
    "source_row": 39,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "M004",
    "poi_name": "CGV Vincom Đà Nẵng",
    "brand": "CGV",
    "category": "Rạp phim",
    "sub_category": "Cinema",
    "city": "Đà Nẵng",
    "district": "Sơn Trà",
    "address": "Vincom Plaza, Sơn Trà",
    "latitude": 16.0719,
    "longitude": 108.2302,
    "rating": 4.3,
    "review_count": 1650,
    "popularity_score": 79.0,
    "price_level": 2,
    "opening_hours": "09:00-23:00",
    "attributes": [
      "rạp phim",
      "trung tâm thương mại",
      "giải trí"
    ],
    "tags": [
      "cinema",
      "mall"
    ],
    "description": "Rạp phim trong trung tâm thương mại Vincom Đà Nẵng.",
    "source_row": 40,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G001",
    "poi_name": "Phúc Long Đống Đa",
    "brand": "Phúc Long",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Hà Nội",
    "district": "Đống Đa",
    "address": "138 Đường Trung Tâm, Đống Đa",
    "latitude": 21.000089,
    "longitude": 105.859995,
    "rating": 4.6,
    "review_count": 959,
    "popularity_score": 52.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "view đẹp",
      "bãi đỗ xe",
      "wifi",
      "mở khuya"
    ],
    "tags": [
      "view-đẹp",
      "bãi-đỗ-xe",
      "wifi",
      "mở-khuya"
    ],
    "description": "Phúc Long Đống Đa tại Đống Đa, Hà Nội, có các đặc điểm: view đẹp, bãi đỗ xe, wifi, mở khuya.",
    "source_row": 41,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G002",
    "poi_name": "Starbucks Cầu Giấy",
    "brand": "Starbucks",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Hà Nội",
    "district": "Cầu Giấy",
    "address": "109 Đường Trung Tâm, Cầu Giấy",
    "latitude": 20.997638,
    "longitude": 105.858782,
    "rating": 4.7,
    "review_count": 2663,
    "popularity_score": 90.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "yên tĩnh",
      "mở khuya",
      "wifi",
      "ngoài trời"
    ],
    "tags": [
      "yên-tĩnh",
      "mở-khuya",
      "wifi",
      "ngoài-trời"
    ],
    "description": "Starbucks Cầu Giấy tại Cầu Giấy, Hà Nội, có các đặc điểm: yên tĩnh, mở khuya, wifi, ngoài trời.",
    "source_row": 42,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G003",
    "poi_name": "Cộng Cà Phê Tây Hồ",
    "brand": "Cộng Cà Phê",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Hà Nội",
    "district": "Tây Hồ",
    "address": "143 Đường Trung Tâm, Tây Hồ",
    "latitude": 21.053593,
    "longitude": 105.839473,
    "rating": 3.9,
    "review_count": 562,
    "popularity_score": 86.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "view đẹp",
      "wifi",
      "yên tĩnh",
      "mở khuya"
    ],
    "tags": [
      "view-đẹp",
      "wifi",
      "yên-tĩnh",
      "mở-khuya"
    ],
    "description": "Cộng Cà Phê Tây Hồ tại Tây Hồ, Hà Nội, có các đặc điểm: view đẹp, wifi, yên tĩnh, mở khuya.",
    "source_row": 43,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G004",
    "poi_name": "BBQ Garden Tây Hồ",
    "brand": "BBQ Garden",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Hà Nội",
    "district": "Tây Hồ",
    "address": "164 Đường Trung Tâm, Tây Hồ",
    "latitude": 21.006651,
    "longitude": 105.82602,
    "rating": 4.4,
    "review_count": 2391,
    "popularity_score": 53.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "lãng mạn",
      "phù hợp trẻ em",
      "hải sản",
      "bãi đỗ xe"
    ],
    "tags": [
      "lãng-mạn",
      "phù-hợp-trẻ-em",
      "hải-sản",
      "bãi-đỗ-xe"
    ],
    "description": "BBQ Garden Tây Hồ tại Tây Hồ, Hà Nội, có các đặc điểm: lãng mạn, phù hợp trẻ em, hải sản, bãi đỗ xe.",
    "source_row": 44,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G005",
    "poi_name": "Sushi House Cầu Giấy",
    "brand": "Sushi House",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Hà Nội",
    "district": "Cầu Giấy",
    "address": "120 Đường Trung Tâm, Cầu Giấy",
    "latitude": 21.034489,
    "longitude": 105.850923,
    "rating": 4.1,
    "review_count": 3333,
    "popularity_score": 61.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "đặt bàn",
      "bãi đỗ xe",
      "giá rẻ",
      "lãng mạn"
    ],
    "tags": [
      "đặt-bàn",
      "bãi-đỗ-xe",
      "giá-rẻ",
      "lãng-mạn"
    ],
    "description": "Sushi House Cầu Giấy tại Cầu Giấy, Hà Nội, có các đặc điểm: đặt bàn, bãi đỗ xe, giá rẻ, lãng mạn.",
    "source_row": 45,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G006",
    "poi_name": "Lẩu Phố Hoàn Kiếm",
    "brand": "Lẩu Phố",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Hà Nội",
    "district": "Hoàn Kiếm",
    "address": "115 Đường Trung Tâm, Hoàn Kiếm",
    "latitude": 21.013656,
    "longitude": 105.887812,
    "rating": 3.9,
    "review_count": 1792,
    "popularity_score": 60.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "hải sản",
      "giá rẻ",
      "lãng mạn",
      "mở khuya"
    ],
    "tags": [
      "hải-sản",
      "giá-rẻ",
      "lãng-mạn",
      "mở-khuya"
    ],
    "description": "Lẩu Phố Hoàn Kiếm tại Hoàn Kiếm, Hà Nội, có các đặc điểm: hải sản, giá rẻ, lãng mạn, mở khuya.",
    "source_row": 46,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G007",
    "poi_name": "Holiday Ba Đình",
    "brand": "Holiday",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Hà Nội",
    "district": "Ba Đình",
    "address": "196 Đường Trung Tâm, Ba Đình",
    "latitude": 21.032565,
    "longitude": 105.874437,
    "rating": 4.5,
    "review_count": 1473,
    "popularity_score": 72.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "giá dưới 2 triệu",
      "gần biển",
      "spa",
      "view đẹp"
    ],
    "tags": [
      "giá-dưới-2-triệu",
      "gần-biển",
      "spa",
      "view-đẹp"
    ],
    "description": "Holiday Ba Đình tại Ba Đình, Hà Nội, có các đặc điểm: giá dưới 2 triệu, gần biển, spa, view đẹp.",
    "source_row": 47,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G008",
    "poi_name": "Lotus Hotel Tây Hồ",
    "brand": "Lotus Hotel",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Hà Nội",
    "district": "Tây Hồ",
    "address": "122 Đường Trung Tâm, Tây Hồ",
    "latitude": 21.042293,
    "longitude": 105.82375,
    "rating": 4.5,
    "review_count": 1348,
    "popularity_score": 91.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "view đẹp",
      "gần biển",
      "giá dưới 2 triệu",
      "bữa sáng"
    ],
    "tags": [
      "view-đẹp",
      "gần-biển",
      "giá-dưới-2-triệu",
      "bữa-sáng"
    ],
    "description": "Lotus Hotel Tây Hồ tại Tây Hồ, Hà Nội, có các đặc điểm: view đẹp, gần biển, giá dưới 2 triệu, bữa sáng.",
    "source_row": 48,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G009",
    "poi_name": "Golden Lotus Đống Đa",
    "brand": "Golden Lotus",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Hà Nội",
    "district": "Đống Đa",
    "address": "119 Đường Trung Tâm, Đống Đa",
    "latitude": 21.018382,
    "longitude": 105.861964,
    "rating": 4.2,
    "review_count": 973,
    "popularity_score": 68.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "giá dưới 2 triệu",
      "spa",
      "bữa sáng",
      "gần biển"
    ],
    "tags": [
      "giá-dưới-2-triệu",
      "spa",
      "bữa-sáng",
      "gần-biển"
    ],
    "description": "Golden Lotus Đống Đa tại Đống Đa, Hà Nội, có các đặc điểm: giá dưới 2 triệu, spa, bữa sáng, gần biển.",
    "source_row": 49,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G010",
    "poi_name": "VPBank Ba Đình",
    "brand": "VPBank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Hà Nội",
    "district": "Ba Đình",
    "address": "43 Đường Trung Tâm, Ba Đình",
    "latitude": 21.024943,
    "longitude": 105.857661,
    "rating": 4.6,
    "review_count": 3435,
    "popularity_score": 77.0,
    "price_level": 3,
    "opening_hours": "24/7",
    "attributes": [
      "rút tiền",
      "gần trung tâm",
      "24/7"
    ],
    "tags": [
      "rút-tiền",
      "gần-trung-tâm",
      "24/7"
    ],
    "description": "VPBank Ba Đình tại Ba Đình, Hà Nội, có các đặc điểm: rút tiền, gần trung tâm, 24/7.",
    "source_row": 50,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G011",
    "poi_name": "Techcombank Cầu Giấy",
    "brand": "Techcombank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Hà Nội",
    "district": "Cầu Giấy",
    "address": "39 Đường Trung Tâm, Cầu Giấy",
    "latitude": 20.999309,
    "longitude": 105.829791,
    "rating": 4.4,
    "review_count": 129,
    "popularity_score": 81.0,
    "price_level": 2,
    "opening_hours": "24/7",
    "attributes": [
      "gần trung tâm",
      "rút tiền",
      "24/7"
    ],
    "tags": [
      "gần-trung-tâm",
      "rút-tiền",
      "24/7"
    ],
    "description": "Techcombank Cầu Giấy tại Cầu Giấy, Hà Nội, có các đặc điểm: gần trung tâm, rút tiền, 24/7.",
    "source_row": 51,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G012",
    "poi_name": "Techcombank Đống Đa",
    "brand": "Techcombank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Hà Nội",
    "district": "Đống Đa",
    "address": "137 Đường Trung Tâm, Đống Đa",
    "latitude": 21.019348,
    "longitude": 105.858844,
    "rating": 4.7,
    "review_count": 2908,
    "popularity_score": 82.0,
    "price_level": 1,
    "opening_hours": "24/7",
    "attributes": [
      "24/7",
      "gần trung tâm",
      "rút tiền"
    ],
    "tags": [
      "24/7",
      "gần-trung-tâm",
      "rút-tiền"
    ],
    "description": "Techcombank Đống Đa tại Đống Đa, Hà Nội, có các đặc điểm: 24/7, gần trung tâm, rút tiền.",
    "source_row": 52,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G013",
    "poi_name": "Trạm xăng Mipec Cầu Giấy",
    "brand": "Mipec",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Hà Nội",
    "district": "Cầu Giấy",
    "address": "124 Đường Trung Tâm, Cầu Giấy",
    "latitude": 21.0379,
    "longitude": 105.823557,
    "rating": 3.9,
    "review_count": 935,
    "popularity_score": 78.0,
    "price_level": 2,
    "opening_hours": "24/7",
    "attributes": [
      "cửa hàng tiện lợi",
      "toilet",
      "bơm lốp",
      "24/7"
    ],
    "tags": [
      "cửa-hàng-tiện-lợi",
      "toilet",
      "bơm-lốp",
      "24/7"
    ],
    "description": "Trạm xăng Mipec Cầu Giấy tại Cầu Giấy, Hà Nội, có các đặc điểm: cửa hàng tiện lợi, toilet, bơm lốp, 24/7.",
    "source_row": 53,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G014",
    "poi_name": "Trạm xăng Shell Việt Hoàn Kiếm",
    "brand": "Shell Việt",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Hà Nội",
    "district": "Hoàn Kiếm",
    "address": "138 Đường Trung Tâm, Hoàn Kiếm",
    "latitude": 21.000603,
    "longitude": 105.844653,
    "rating": 3.8,
    "review_count": 931,
    "popularity_score": 89.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "24/7",
      "cửa hàng tiện lợi",
      "bơm lốp",
      "toilet"
    ],
    "tags": [
      "24/7",
      "cửa-hàng-tiện-lợi",
      "bơm-lốp",
      "toilet"
    ],
    "description": "Trạm xăng Shell Việt Hoàn Kiếm tại Hoàn Kiếm, Hà Nội, có các đặc điểm: 24/7, cửa hàng tiện lợi, bơm lốp, toilet.",
    "source_row": 54,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G015",
    "poi_name": "Trạm xăng Shell Việt Ba Đình",
    "brand": "Shell Việt",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Hà Nội",
    "district": "Ba Đình",
    "address": "32 Đường Trung Tâm, Ba Đình",
    "latitude": 21.001575,
    "longitude": 105.853365,
    "rating": 4.7,
    "review_count": 2047,
    "popularity_score": 80.0,
    "price_level": 3,
    "opening_hours": "24/7",
    "attributes": [
      "bơm lốp",
      "cửa hàng tiện lợi",
      "toilet",
      "24/7"
    ],
    "tags": [
      "bơm-lốp",
      "cửa-hàng-tiện-lợi",
      "toilet",
      "24/7"
    ],
    "description": "Trạm xăng Shell Việt Ba Đình tại Ba Đình, Hà Nội, có các đặc điểm: bơm lốp, cửa hàng tiện lợi, toilet, 24/7.",
    "source_row": 55,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G016",
    "poi_name": "Aeon Mall Hoàn Kiếm",
    "brand": "Aeon Mall",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Hà Nội",
    "district": "Hoàn Kiếm",
    "address": "123 Đường Trung Tâm, Hoàn Kiếm",
    "latitude": 21.05152,
    "longitude": 105.830501,
    "rating": 3.8,
    "review_count": 2243,
    "popularity_score": 73.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "mua sắm",
      "rạp phim",
      "bãi đỗ xe",
      "ăn uống"
    ],
    "tags": [
      "mua-sắm",
      "rạp-phim",
      "bãi-đỗ-xe",
      "ăn-uống"
    ],
    "description": "Aeon Mall Hoàn Kiếm tại Hoàn Kiếm, Hà Nội, có các đặc điểm: mua sắm, rạp phim, bãi đỗ xe, ăn uống.",
    "source_row": 56,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G017",
    "poi_name": "Vincom Tây Hồ",
    "brand": "Vincom",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Hà Nội",
    "district": "Tây Hồ",
    "address": "179 Đường Trung Tâm, Tây Hồ",
    "latitude": 21.052681,
    "longitude": 105.855488,
    "rating": 4.6,
    "review_count": 1536,
    "popularity_score": 64.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "gia đình",
      "rạp phim",
      "bãi đỗ xe",
      "mua sắm"
    ],
    "tags": [
      "gia-đình",
      "rạp-phim",
      "bãi-đỗ-xe",
      "mua-sắm"
    ],
    "description": "Vincom Tây Hồ tại Tây Hồ, Hà Nội, có các đặc điểm: gia đình, rạp phim, bãi đỗ xe, mua sắm.",
    "source_row": 57,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G018",
    "poi_name": "Aeon Mall Ba Đình",
    "brand": "Aeon Mall",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Hà Nội",
    "district": "Ba Đình",
    "address": "52 Đường Trung Tâm, Ba Đình",
    "latitude": 21.029735,
    "longitude": 105.844089,
    "rating": 3.8,
    "review_count": 194,
    "popularity_score": 67.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "ăn uống",
      "bãi đỗ xe",
      "rạp phim",
      "mua sắm"
    ],
    "tags": [
      "ăn-uống",
      "bãi-đỗ-xe",
      "rạp-phim",
      "mua-sắm"
    ],
    "description": "Aeon Mall Ba Đình tại Ba Đình, Hà Nội, có các đặc điểm: ăn uống, bãi đỗ xe, rạp phim, mua sắm.",
    "source_row": 58,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G019",
    "poi_name": "Phúc Long Bình Thạnh",
    "brand": "Phúc Long",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "94 Đường Trung Tâm, Bình Thạnh",
    "latitude": 10.747538,
    "longitude": 106.673051,
    "rating": 4.2,
    "review_count": 1463,
    "popularity_score": 63.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "bãi đỗ xe",
      "phòng họp",
      "mở khuya",
      "phù hợp làm việc"
    ],
    "tags": [
      "bãi-đỗ-xe",
      "phòng-họp",
      "mở-khuya",
      "phù-hợp-làm-việc"
    ],
    "description": "Phúc Long Bình Thạnh tại Bình Thạnh, TP.HCM, có các đặc điểm: bãi đỗ xe, phòng họp, mở khuya, phù hợp làm việc.",
    "source_row": 59,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G020",
    "poi_name": "Cộng Cà Phê Quận 7",
    "brand": "Cộng Cà Phê",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "165 Đường Trung Tâm, Quận 7",
    "latitude": 10.747834,
    "longitude": 106.712141,
    "rating": 4.6,
    "review_count": 3284,
    "popularity_score": 62.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "wifi",
      "phòng họp",
      "bãi đỗ xe",
      "phù hợp làm việc"
    ],
    "tags": [
      "wifi",
      "phòng-họp",
      "bãi-đỗ-xe",
      "phù-hợp-làm-việc"
    ],
    "description": "Cộng Cà Phê Quận 7 tại Quận 7, TP.HCM, có các đặc điểm: wifi, phòng họp, bãi đỗ xe, phù hợp làm việc.",
    "source_row": 60,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G021",
    "poi_name": "Starbucks Quận 3",
    "brand": "Starbucks",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "TP.HCM",
    "district": "Quận 3",
    "address": "119 Đường Trung Tâm, Quận 3",
    "latitude": 10.769997,
    "longitude": 106.732176,
    "rating": 4.5,
    "review_count": 776,
    "popularity_score": 58.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "bãi đỗ xe",
      "wifi",
      "mở khuya",
      "phòng họp"
    ],
    "tags": [
      "bãi-đỗ-xe",
      "wifi",
      "mở-khuya",
      "phòng-họp"
    ],
    "description": "Starbucks Quận 3 tại Quận 3, TP.HCM, có các đặc điểm: bãi đỗ xe, wifi, mở khuya, phòng họp.",
    "source_row": 61,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G022",
    "poi_name": "Lẩu Phố Quận 3",
    "brand": "Lẩu Phố",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "TP.HCM",
    "district": "Quận 3",
    "address": "122 Đường Trung Tâm, Quận 3",
    "latitude": 10.787909,
    "longitude": 106.690429,
    "rating": 4.3,
    "review_count": 616,
    "popularity_score": 51.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "giá rẻ",
      "lãng mạn",
      "hải sản",
      "bãi đỗ xe"
    ],
    "tags": [
      "giá-rẻ",
      "lãng-mạn",
      "hải-sản",
      "bãi-đỗ-xe"
    ],
    "description": "Lẩu Phố Quận 3 tại Quận 3, TP.HCM, có các đặc điểm: giá rẻ, lãng mạn, hải sản, bãi đỗ xe.",
    "source_row": 62,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G023",
    "poi_name": "Lẩu Phố Quận 1",
    "brand": "Lẩu Phố",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "55 Đường Trung Tâm, Quận 1",
    "latitude": 10.74386,
    "longitude": 106.680795,
    "rating": 4.3,
    "review_count": 3208,
    "popularity_score": 87.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "lãng mạn",
      "bãi đỗ xe",
      "giá rẻ",
      "phù hợp trẻ em"
    ],
    "tags": [
      "lãng-mạn",
      "bãi-đỗ-xe",
      "giá-rẻ",
      "phù-hợp-trẻ-em"
    ],
    "description": "Lẩu Phố Quận 1 tại Quận 1, TP.HCM, có các đặc điểm: lãng mạn, bãi đỗ xe, giá rẻ, phù hợp trẻ em.",
    "source_row": 63,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G024",
    "poi_name": "Lẩu Phố Bình Thạnh",
    "brand": "Lẩu Phố",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "91 Đường Trung Tâm, Bình Thạnh",
    "latitude": 10.804739,
    "longitude": 106.712273,
    "rating": 4.5,
    "review_count": 2196,
    "popularity_score": 76.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "bãi đỗ xe",
      "lãng mạn",
      "phù hợp gia đình",
      "mở khuya"
    ],
    "tags": [
      "bãi-đỗ-xe",
      "lãng-mạn",
      "phù-hợp-gia-đình",
      "mở-khuya"
    ],
    "description": "Lẩu Phố Bình Thạnh tại Bình Thạnh, TP.HCM, có các đặc điểm: bãi đỗ xe, lãng mạn, phù hợp gia đình, mở khuya.",
    "source_row": 64,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G025",
    "poi_name": "Fusion Quận 7",
    "brand": "Fusion",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "156 Đường Trung Tâm, Quận 7",
    "latitude": 10.742175,
    "longitude": 106.721842,
    "rating": 4.0,
    "review_count": 2019,
    "popularity_score": 89.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "gần biển",
      "giá dưới 2 triệu",
      "phù hợp gia đình",
      "hồ bơi"
    ],
    "tags": [
      "gần-biển",
      "giá-dưới-2-triệu",
      "phù-hợp-gia-đình",
      "hồ-bơi"
    ],
    "description": "Fusion Quận 7 tại Quận 7, TP.HCM, có các đặc điểm: gần biển, giá dưới 2 triệu, phù hợp gia đình, hồ bơi.",
    "source_row": 65,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G026",
    "poi_name": "Mường Thanh Quận 7",
    "brand": "Mường Thanh",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "143 Đường Trung Tâm, Quận 7",
    "latitude": 10.775674,
    "longitude": 106.720254,
    "rating": 4.6,
    "review_count": 312,
    "popularity_score": 65.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "spa",
      "view đẹp",
      "phù hợp công tác",
      "giá dưới 2 triệu"
    ],
    "tags": [
      "spa",
      "view-đẹp",
      "phù-hợp-công-tác",
      "giá-dưới-2-triệu"
    ],
    "description": "Mường Thanh Quận 7 tại Quận 7, TP.HCM, có các đặc điểm: spa, view đẹp, phù hợp công tác, giá dưới 2 triệu.",
    "source_row": 66,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G027",
    "poi_name": "Mường Thanh Bình Thạnh",
    "brand": "Mường Thanh",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "8 Đường Trung Tâm, Bình Thạnh",
    "latitude": 10.7951,
    "longitude": 106.729774,
    "rating": 4.2,
    "review_count": 2588,
    "popularity_score": 82.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "hồ bơi",
      "phù hợp công tác",
      "phù hợp gia đình",
      "giá dưới 2 triệu"
    ],
    "tags": [
      "hồ-bơi",
      "phù-hợp-công-tác",
      "phù-hợp-gia-đình",
      "giá-dưới-2-triệu"
    ],
    "description": "Mường Thanh Bình Thạnh tại Bình Thạnh, TP.HCM, có các đặc điểm: hồ bơi, phù hợp công tác, phù hợp gia đình, giá dưới 2 triệu.",
    "source_row": 67,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G028",
    "poi_name": "VPBank Bình Thạnh",
    "brand": "VPBank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "179 Đường Trung Tâm, Bình Thạnh",
    "latitude": 10.778525,
    "longitude": 106.727218,
    "rating": 4.6,
    "review_count": 2371,
    "popularity_score": 62.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "gần trung tâm",
      "rút tiền",
      "24/7"
    ],
    "tags": [
      "gần-trung-tâm",
      "rút-tiền",
      "24/7"
    ],
    "description": "VPBank Bình Thạnh tại Bình Thạnh, TP.HCM, có các đặc điểm: gần trung tâm, rút tiền, 24/7.",
    "source_row": 68,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G029",
    "poi_name": "VPBank Quận 3",
    "brand": "VPBank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "TP.HCM",
    "district": "Quận 3",
    "address": "81 Đường Trung Tâm, Quận 3",
    "latitude": 10.746978,
    "longitude": 106.682745,
    "rating": 3.9,
    "review_count": 2822,
    "popularity_score": 69.0,
    "price_level": 1,
    "opening_hours": "24/7",
    "attributes": [
      "24/7",
      "rút tiền",
      "gần trung tâm"
    ],
    "tags": [
      "24/7",
      "rút-tiền",
      "gần-trung-tâm"
    ],
    "description": "VPBank Quận 3 tại Quận 3, TP.HCM, có các đặc điểm: 24/7, rút tiền, gần trung tâm.",
    "source_row": 69,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G030",
    "poi_name": "Techcombank Quận 3",
    "brand": "Techcombank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "TP.HCM",
    "district": "Quận 3",
    "address": "120 Đường Trung Tâm, Quận 3",
    "latitude": 10.757271,
    "longitude": 106.732575,
    "rating": 4.2,
    "review_count": 2075,
    "popularity_score": 60.0,
    "price_level": 2,
    "opening_hours": "24/7",
    "attributes": [
      "24/7",
      "rút tiền",
      "gần trung tâm"
    ],
    "tags": [
      "24/7",
      "rút-tiền",
      "gần-trung-tâm"
    ],
    "description": "Techcombank Quận 3 tại Quận 3, TP.HCM, có các đặc điểm: 24/7, rút tiền, gần trung tâm.",
    "source_row": 70,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G031",
    "poi_name": "Trạm xăng Mipec Quận 3",
    "brand": "Mipec",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "TP.HCM",
    "district": "Quận 3",
    "address": "92 Đường Trung Tâm, Quận 3",
    "latitude": 10.764197,
    "longitude": 106.716451,
    "rating": 3.8,
    "review_count": 2349,
    "popularity_score": 79.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "cửa hàng tiện lợi",
      "toilet",
      "bơm lốp",
      "24/7"
    ],
    "tags": [
      "cửa-hàng-tiện-lợi",
      "toilet",
      "bơm-lốp",
      "24/7"
    ],
    "description": "Trạm xăng Mipec Quận 3 tại Quận 3, TP.HCM, có các đặc điểm: cửa hàng tiện lợi, toilet, bơm lốp, 24/7.",
    "source_row": 71,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G032",
    "poi_name": "Trạm xăng Mipec Quận 1",
    "brand": "Mipec",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "29 Đường Trung Tâm, Quận 1",
    "latitude": 10.810856,
    "longitude": 106.721085,
    "rating": 4.7,
    "review_count": 509,
    "popularity_score": 55.0,
    "price_level": 3,
    "opening_hours": "24/7",
    "attributes": [
      "bơm lốp",
      "cửa hàng tiện lợi",
      "toilet",
      "24/7"
    ],
    "tags": [
      "bơm-lốp",
      "cửa-hàng-tiện-lợi",
      "toilet",
      "24/7"
    ],
    "description": "Trạm xăng Mipec Quận 1 tại Quận 1, TP.HCM, có các đặc điểm: bơm lốp, cửa hàng tiện lợi, toilet, 24/7.",
    "source_row": 72,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G033",
    "poi_name": "Trạm xăng Petrolimex Bình Thạnh",
    "brand": "Petrolimex",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "174 Đường Trung Tâm, Bình Thạnh",
    "latitude": 10.799229,
    "longitude": 106.684003,
    "rating": 3.9,
    "review_count": 2188,
    "popularity_score": 86.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "toilet",
      "cửa hàng tiện lợi",
      "24/7",
      "bơm lốp"
    ],
    "tags": [
      "toilet",
      "cửa-hàng-tiện-lợi",
      "24/7",
      "bơm-lốp"
    ],
    "description": "Trạm xăng Petrolimex Bình Thạnh tại Bình Thạnh, TP.HCM, có các đặc điểm: toilet, cửa hàng tiện lợi, 24/7, bơm lốp.",
    "source_row": 73,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G034",
    "poi_name": "Vincom Bình Thạnh",
    "brand": "Vincom",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "109 Đường Trung Tâm, Bình Thạnh",
    "latitude": 10.80457,
    "longitude": 106.684725,
    "rating": 3.8,
    "review_count": 442,
    "popularity_score": 66.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "rạp phim",
      "mua sắm",
      "gia đình",
      "bãi đỗ xe"
    ],
    "tags": [
      "rạp-phim",
      "mua-sắm",
      "gia-đình",
      "bãi-đỗ-xe"
    ],
    "description": "Vincom Bình Thạnh tại Bình Thạnh, TP.HCM, có các đặc điểm: rạp phim, mua sắm, gia đình, bãi đỗ xe.",
    "source_row": 74,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G035",
    "poi_name": "Aeon Mall Quận 7",
    "brand": "Aeon Mall",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "3 Đường Trung Tâm, Quận 7",
    "latitude": 10.765641,
    "longitude": 106.704614,
    "rating": 4.6,
    "review_count": 1177,
    "popularity_score": 89.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "mua sắm",
      "rạp phim",
      "gia đình",
      "ăn uống"
    ],
    "tags": [
      "mua-sắm",
      "rạp-phim",
      "gia-đình",
      "ăn-uống"
    ],
    "description": "Aeon Mall Quận 7 tại Quận 7, TP.HCM, có các đặc điểm: mua sắm, rạp phim, gia đình, ăn uống.",
    "source_row": 75,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G036",
    "poi_name": "Aeon Mall Quận 1",
    "brand": "Aeon Mall",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "TP.HCM",
    "district": "Quận 1",
    "address": "47 Đường Trung Tâm, Quận 1",
    "latitude": 10.756024,
    "longitude": 106.687739,
    "rating": 4.1,
    "review_count": 3190,
    "popularity_score": 63.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "mua sắm",
      "ăn uống",
      "bãi đỗ xe",
      "gia đình"
    ],
    "tags": [
      "mua-sắm",
      "ăn-uống",
      "bãi-đỗ-xe",
      "gia-đình"
    ],
    "description": "Aeon Mall Quận 1 tại Quận 1, TP.HCM, có các đặc điểm: mua sắm, ăn uống, bãi đỗ xe, gia đình.",
    "source_row": 76,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G037",
    "poi_name": "Cộng Cà Phê Thanh Khê",
    "brand": "Cộng Cà Phê",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Đà Nẵng",
    "district": "Thanh Khê",
    "address": "65 Đường Trung Tâm, Thanh Khê",
    "latitude": 16.014686,
    "longitude": 108.17309,
    "rating": 4.3,
    "review_count": 856,
    "popularity_score": 82.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "phù hợp làm việc",
      "mở khuya",
      "view đẹp",
      "wifi"
    ],
    "tags": [
      "phù-hợp-làm-việc",
      "mở-khuya",
      "view-đẹp",
      "wifi"
    ],
    "description": "Cộng Cà Phê Thanh Khê tại Thanh Khê, Đà Nẵng, có các đặc điểm: phù hợp làm việc, mở khuya, view đẹp, wifi.",
    "source_row": 77,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G038",
    "poi_name": "Starbucks Sơn Trà",
    "brand": "Starbucks",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Đà Nẵng",
    "district": "Sơn Trà",
    "address": "169 Đường Trung Tâm, Sơn Trà",
    "latitude": 16.04675,
    "longitude": 108.230223,
    "rating": 4.2,
    "review_count": 2155,
    "popularity_score": 69.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "yên tĩnh",
      "bãi đỗ xe",
      "view đẹp",
      "phòng họp"
    ],
    "tags": [
      "yên-tĩnh",
      "bãi-đỗ-xe",
      "view-đẹp",
      "phòng-họp"
    ],
    "description": "Starbucks Sơn Trà tại Sơn Trà, Đà Nẵng, có các đặc điểm: yên tĩnh, bãi đỗ xe, view đẹp, phòng họp.",
    "source_row": 78,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G039",
    "poi_name": "Katinat Sơn Trà",
    "brand": "Katinat",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Đà Nẵng",
    "district": "Sơn Trà",
    "address": "104 Đường Trung Tâm, Sơn Trà",
    "latitude": 16.081361,
    "longitude": 108.240532,
    "rating": 4.6,
    "review_count": 138,
    "popularity_score": 54.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "phòng họp",
      "view đẹp",
      "bãi đỗ xe",
      "yên tĩnh"
    ],
    "tags": [
      "phòng-họp",
      "view-đẹp",
      "bãi-đỗ-xe",
      "yên-tĩnh"
    ],
    "description": "Katinat Sơn Trà tại Sơn Trà, Đà Nẵng, có các đặc điểm: phòng họp, view đẹp, bãi đỗ xe, yên tĩnh.",
    "source_row": 79,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G040",
    "poi_name": "Quán Ngon Thanh Khê",
    "brand": "Quán Ngon",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Đà Nẵng",
    "district": "Thanh Khê",
    "address": "130 Đường Trung Tâm, Thanh Khê",
    "latitude": 16.059038,
    "longitude": 108.191535,
    "rating": 4.0,
    "review_count": 1280,
    "popularity_score": 52.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "phù hợp gia đình",
      "phù hợp trẻ em",
      "mở khuya",
      "món Việt"
    ],
    "tags": [
      "phù-hợp-gia-đình",
      "phù-hợp-trẻ-em",
      "mở-khuya",
      "món-Việt"
    ],
    "description": "Quán Ngon Thanh Khê tại Thanh Khê, Đà Nẵng, có các đặc điểm: phù hợp gia đình, phù hợp trẻ em, mở khuya, món Việt.",
    "source_row": 80,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G041",
    "poi_name": "Quán Ngon Sơn Trà",
    "brand": "Quán Ngon",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Đà Nẵng",
    "district": "Sơn Trà",
    "address": "94 Đường Trung Tâm, Sơn Trà",
    "latitude": 16.079425,
    "longitude": 108.239884,
    "rating": 4.3,
    "review_count": 1081,
    "popularity_score": 52.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "hải sản",
      "giá rẻ",
      "phù hợp gia đình",
      "lãng mạn"
    ],
    "tags": [
      "hải-sản",
      "giá-rẻ",
      "phù-hợp-gia-đình",
      "lãng-mạn"
    ],
    "description": "Quán Ngon Sơn Trà tại Sơn Trà, Đà Nẵng, có các đặc điểm: hải sản, giá rẻ, phù hợp gia đình, lãng mạn.",
    "source_row": 81,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G042",
    "poi_name": "Bếp Việt Sơn Trà",
    "brand": "Bếp Việt",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Đà Nẵng",
    "district": "Sơn Trà",
    "address": "22 Đường Trung Tâm, Sơn Trà",
    "latitude": 16.045325,
    "longitude": 108.206993,
    "rating": 4.0,
    "review_count": 2147,
    "popularity_score": 50.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "lãng mạn",
      "phù hợp gia đình",
      "đặt bàn",
      "món Việt"
    ],
    "tags": [
      "lãng-mạn",
      "phù-hợp-gia-đình",
      "đặt-bàn",
      "món-Việt"
    ],
    "description": "Bếp Việt Sơn Trà tại Sơn Trà, Đà Nẵng, có các đặc điểm: lãng mạn, phù hợp gia đình, đặt bàn, món Việt.",
    "source_row": 82,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G043",
    "poi_name": "Lotus Hotel Ngũ Hành Sơn",
    "brand": "Lotus Hotel",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Đà Nẵng",
    "district": "Ngũ Hành Sơn",
    "address": "11 Đường Trung Tâm, Ngũ Hành Sơn",
    "latitude": 16.039679,
    "longitude": 108.192775,
    "rating": 4.4,
    "review_count": 426,
    "popularity_score": 87.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "hồ bơi",
      "view đẹp",
      "phù hợp gia đình",
      "phù hợp công tác"
    ],
    "tags": [
      "hồ-bơi",
      "view-đẹp",
      "phù-hợp-gia-đình",
      "phù-hợp-công-tác"
    ],
    "description": "Lotus Hotel Ngũ Hành Sơn tại Ngũ Hành Sơn, Đà Nẵng, có các đặc điểm: hồ bơi, view đẹp, phù hợp gia đình, phù hợp công tác.",
    "source_row": 83,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G044",
    "poi_name": "Holiday Liên Chiểu",
    "brand": "Holiday",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Đà Nẵng",
    "district": "Liên Chiểu",
    "address": "73 Đường Trung Tâm, Liên Chiểu",
    "latitude": 16.062791,
    "longitude": 108.216825,
    "rating": 3.8,
    "review_count": 3008,
    "popularity_score": 82.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "spa",
      "view đẹp",
      "phù hợp gia đình",
      "hồ bơi"
    ],
    "tags": [
      "spa",
      "view-đẹp",
      "phù-hợp-gia-đình",
      "hồ-bơi"
    ],
    "description": "Holiday Liên Chiểu tại Liên Chiểu, Đà Nẵng, có các đặc điểm: spa, view đẹp, phù hợp gia đình, hồ bơi.",
    "source_row": 84,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G045",
    "poi_name": "Fusion Liên Chiểu",
    "brand": "Fusion",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Đà Nẵng",
    "district": "Liên Chiểu",
    "address": "183 Đường Trung Tâm, Liên Chiểu",
    "latitude": 16.059903,
    "longitude": 108.220333,
    "rating": 4.0,
    "review_count": 207,
    "popularity_score": 52.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "gần biển",
      "giá dưới 2 triệu",
      "spa",
      "phù hợp công tác"
    ],
    "tags": [
      "gần-biển",
      "giá-dưới-2-triệu",
      "spa",
      "phù-hợp-công-tác"
    ],
    "description": "Fusion Liên Chiểu tại Liên Chiểu, Đà Nẵng, có các đặc điểm: gần biển, giá dưới 2 triệu, spa, phù hợp công tác.",
    "source_row": 85,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G046",
    "poi_name": "Vietcombank Ngũ Hành Sơn",
    "brand": "Vietcombank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Đà Nẵng",
    "district": "Ngũ Hành Sơn",
    "address": "161 Đường Trung Tâm, Ngũ Hành Sơn",
    "latitude": 16.013419,
    "longitude": 108.209001,
    "rating": 4.0,
    "review_count": 1160,
    "popularity_score": 50.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "rút tiền",
      "gần trung tâm",
      "24/7"
    ],
    "tags": [
      "rút-tiền",
      "gần-trung-tâm",
      "24/7"
    ],
    "description": "Vietcombank Ngũ Hành Sơn tại Ngũ Hành Sơn, Đà Nẵng, có các đặc điểm: rút tiền, gần trung tâm, 24/7.",
    "source_row": 86,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G047",
    "poi_name": "ACB Hải Châu",
    "brand": "ACB",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "191 Đường Trung Tâm, Hải Châu",
    "latitude": 16.063675,
    "longitude": 108.189454,
    "rating": 3.9,
    "review_count": 1167,
    "popularity_score": 65.0,
    "price_level": 2,
    "opening_hours": "24/7",
    "attributes": [
      "gần trung tâm",
      "24/7",
      "rút tiền"
    ],
    "tags": [
      "gần-trung-tâm",
      "24/7",
      "rút-tiền"
    ],
    "description": "ACB Hải Châu tại Hải Châu, Đà Nẵng, có các đặc điểm: gần trung tâm, 24/7, rút tiền.",
    "source_row": 87,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G048",
    "poi_name": "VPBank Sơn Trà",
    "brand": "VPBank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Đà Nẵng",
    "district": "Sơn Trà",
    "address": "123 Đường Trung Tâm, Sơn Trà",
    "latitude": 16.075833,
    "longitude": 108.191912,
    "rating": 3.8,
    "review_count": 2671,
    "popularity_score": 91.0,
    "price_level": 2,
    "opening_hours": "24/7",
    "attributes": [
      "rút tiền",
      "gần trung tâm",
      "24/7"
    ],
    "tags": [
      "rút-tiền",
      "gần-trung-tâm",
      "24/7"
    ],
    "description": "VPBank Sơn Trà tại Sơn Trà, Đà Nẵng, có các đặc điểm: rút tiền, gần trung tâm, 24/7.",
    "source_row": 88,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G049",
    "poi_name": "Trạm xăng PVOIL Hải Châu",
    "brand": "PVOIL",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "4 Đường Trung Tâm, Hải Châu",
    "latitude": 16.045869,
    "longitude": 108.205806,
    "rating": 4.7,
    "review_count": 487,
    "popularity_score": 63.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "bơm lốp",
      "toilet",
      "cửa hàng tiện lợi",
      "24/7"
    ],
    "tags": [
      "bơm-lốp",
      "toilet",
      "cửa-hàng-tiện-lợi",
      "24/7"
    ],
    "description": "Trạm xăng PVOIL Hải Châu tại Hải Châu, Đà Nẵng, có các đặc điểm: bơm lốp, toilet, cửa hàng tiện lợi, 24/7.",
    "source_row": 89,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G050",
    "poi_name": "Trạm xăng Shell Việt Ngũ Hành Sơn",
    "brand": "Shell Việt",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Đà Nẵng",
    "district": "Ngũ Hành Sơn",
    "address": "141 Đường Trung Tâm, Ngũ Hành Sơn",
    "latitude": 16.026048,
    "longitude": 108.240269,
    "rating": 4.6,
    "review_count": 151,
    "popularity_score": 68.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "cửa hàng tiện lợi",
      "toilet",
      "bơm lốp",
      "24/7"
    ],
    "tags": [
      "cửa-hàng-tiện-lợi",
      "toilet",
      "bơm-lốp",
      "24/7"
    ],
    "description": "Trạm xăng Shell Việt Ngũ Hành Sơn tại Ngũ Hành Sơn, Đà Nẵng, có các đặc điểm: cửa hàng tiện lợi, toilet, bơm lốp, 24/7.",
    "source_row": 90,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G051",
    "poi_name": "Trạm xăng Mipec Hải Châu",
    "brand": "Mipec",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "20 Đường Trung Tâm, Hải Châu",
    "latitude": 16.052803,
    "longitude": 108.181722,
    "rating": 4.3,
    "review_count": 1552,
    "popularity_score": 58.0,
    "price_level": 3,
    "opening_hours": "24/7",
    "attributes": [
      "bơm lốp",
      "toilet",
      "24/7",
      "cửa hàng tiện lợi"
    ],
    "tags": [
      "bơm-lốp",
      "toilet",
      "24/7",
      "cửa-hàng-tiện-lợi"
    ],
    "description": "Trạm xăng Mipec Hải Châu tại Hải Châu, Đà Nẵng, có các đặc điểm: bơm lốp, toilet, 24/7, cửa hàng tiện lợi.",
    "source_row": 91,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G052",
    "poi_name": "Lotte Mall Hải Châu",
    "brand": "Lotte Mall",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "7 Đường Trung Tâm, Hải Châu",
    "latitude": 16.023235,
    "longitude": 108.238297,
    "rating": 4.4,
    "review_count": 1740,
    "popularity_score": 69.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "ăn uống",
      "bãi đỗ xe",
      "gia đình",
      "rạp phim"
    ],
    "tags": [
      "ăn-uống",
      "bãi-đỗ-xe",
      "gia-đình",
      "rạp-phim"
    ],
    "description": "Lotte Mall Hải Châu tại Hải Châu, Đà Nẵng, có các đặc điểm: ăn uống, bãi đỗ xe, gia đình, rạp phim.",
    "source_row": 92,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G053",
    "poi_name": "Lotte Mall Thanh Khê",
    "brand": "Lotte Mall",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Đà Nẵng",
    "district": "Thanh Khê",
    "address": "1 Đường Trung Tâm, Thanh Khê",
    "latitude": 16.034818,
    "longitude": 108.195479,
    "rating": 4.2,
    "review_count": 881,
    "popularity_score": 50.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "bãi đỗ xe",
      "rạp phim",
      "mua sắm",
      "ăn uống"
    ],
    "tags": [
      "bãi-đỗ-xe",
      "rạp-phim",
      "mua-sắm",
      "ăn-uống"
    ],
    "description": "Lotte Mall Thanh Khê tại Thanh Khê, Đà Nẵng, có các đặc điểm: bãi đỗ xe, rạp phim, mua sắm, ăn uống.",
    "source_row": 93,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G054",
    "poi_name": "Lotte Mall Ngũ Hành Sơn",
    "brand": "Lotte Mall",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Đà Nẵng",
    "district": "Ngũ Hành Sơn",
    "address": "93 Đường Trung Tâm, Ngũ Hành Sơn",
    "latitude": 16.076879,
    "longitude": 108.224696,
    "rating": 4.6,
    "review_count": 1229,
    "popularity_score": 56.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "mua sắm",
      "bãi đỗ xe",
      "ăn uống",
      "gia đình"
    ],
    "tags": [
      "mua-sắm",
      "bãi-đỗ-xe",
      "ăn-uống",
      "gia-đình"
    ],
    "description": "Lotte Mall Ngũ Hành Sơn tại Ngũ Hành Sơn, Đà Nẵng, có các đặc điểm: mua sắm, bãi đỗ xe, ăn uống, gia đình.",
    "source_row": 94,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G055",
    "poi_name": "The Coffee House Phường 3",
    "brand": "The Coffee House",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Đà Lạt",
    "district": "Phường 3",
    "address": "131 Đường Trung Tâm, Phường 3",
    "latitude": 11.927492,
    "longitude": 108.477423,
    "rating": 4.5,
    "review_count": 1832,
    "popularity_score": 51.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "phù hợp làm việc",
      "yên tĩnh",
      "mở khuya",
      "phòng họp"
    ],
    "tags": [
      "phù-hợp-làm-việc",
      "yên-tĩnh",
      "mở-khuya",
      "phòng-họp"
    ],
    "description": "The Coffee House Phường 3 tại Phường 3, Đà Lạt, có các đặc điểm: phù hợp làm việc, yên tĩnh, mở khuya, phòng họp.",
    "source_row": 95,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G056",
    "poi_name": "Cộng Cà Phê Phường 8",
    "brand": "Cộng Cà Phê",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Đà Lạt",
    "district": "Phường 8",
    "address": "188 Đường Trung Tâm, Phường 8",
    "latitude": 11.934162,
    "longitude": 108.466344,
    "rating": 3.9,
    "review_count": 1252,
    "popularity_score": 81.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "phòng họp",
      "bãi đỗ xe",
      "wifi",
      "view đẹp"
    ],
    "tags": [
      "phòng-họp",
      "bãi-đỗ-xe",
      "wifi",
      "view-đẹp"
    ],
    "description": "Cộng Cà Phê Phường 8 tại Phường 8, Đà Lạt, có các đặc điểm: phòng họp, bãi đỗ xe, wifi, view đẹp.",
    "source_row": 96,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G057",
    "poi_name": "Phúc Long Phường 8",
    "brand": "Phúc Long",
    "category": "Quán cà phê",
    "sub_category": "Coffee",
    "city": "Đà Lạt",
    "district": "Phường 8",
    "address": "73 Đường Trung Tâm, Phường 8",
    "latitude": 11.926244,
    "longitude": 108.475032,
    "rating": 4.7,
    "review_count": 1145,
    "popularity_score": 75.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "phù hợp làm việc",
      "phòng họp",
      "view đẹp",
      "mở khuya"
    ],
    "tags": [
      "phù-hợp-làm-việc",
      "phòng-họp",
      "view-đẹp",
      "mở-khuya"
    ],
    "description": "Phúc Long Phường 8 tại Phường 8, Đà Lạt, có các đặc điểm: phù hợp làm việc, phòng họp, view đẹp, mở khuya.",
    "source_row": 97,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G058",
    "poi_name": "Nhà hàng Biển Xanh Phường 3",
    "brand": "Nhà hàng Biển Xanh",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Đà Lạt",
    "district": "Phường 3",
    "address": "165 Đường Trung Tâm, Phường 3",
    "latitude": 11.916716,
    "longitude": 108.437851,
    "rating": 4.6,
    "review_count": 2116,
    "popularity_score": 85.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "đặt bàn",
      "bãi đỗ xe",
      "phù hợp gia đình",
      "phù hợp trẻ em"
    ],
    "tags": [
      "đặt-bàn",
      "bãi-đỗ-xe",
      "phù-hợp-gia-đình",
      "phù-hợp-trẻ-em"
    ],
    "description": "Nhà hàng Biển Xanh Phường 3 tại Phường 3, Đà Lạt, có các đặc điểm: đặt bàn, bãi đỗ xe, phù hợp gia đình, phù hợp trẻ em.",
    "source_row": 98,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G059",
    "poi_name": "Bếp Việt Phường 4",
    "brand": "Bếp Việt",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Đà Lạt",
    "district": "Phường 4",
    "address": "50 Đường Trung Tâm, Phường 4",
    "latitude": 11.922486,
    "longitude": 108.435529,
    "rating": 4.3,
    "review_count": 1387,
    "popularity_score": 65.0,
    "price_level": 3,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "giá rẻ",
      "bãi đỗ xe",
      "phù hợp trẻ em",
      "hải sản"
    ],
    "tags": [
      "giá-rẻ",
      "bãi-đỗ-xe",
      "phù-hợp-trẻ-em",
      "hải-sản"
    ],
    "description": "Bếp Việt Phường 4 tại Phường 4, Đà Lạt, có các đặc điểm: giá rẻ, bãi đỗ xe, phù hợp trẻ em, hải sản.",
    "source_row": 99,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G060",
    "poi_name": "BBQ Garden Phường 3",
    "brand": "BBQ Garden",
    "category": "Nhà hàng",
    "sub_category": "Restaurant",
    "city": "Đà Lạt",
    "district": "Phường 3",
    "address": "99 Đường Trung Tâm, Phường 3",
    "latitude": 11.934372,
    "longitude": 108.459992,
    "rating": 4.1,
    "review_count": 1465,
    "popularity_score": 53.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "món Việt",
      "phù hợp gia đình",
      "mở khuya",
      "đặt bàn"
    ],
    "tags": [
      "món-Việt",
      "phù-hợp-gia-đình",
      "mở-khuya",
      "đặt-bàn"
    ],
    "description": "BBQ Garden Phường 3 tại Phường 3, Đà Lạt, có các đặc điểm: món Việt, phù hợp gia đình, mở khuya, đặt bàn.",
    "source_row": 100,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G061",
    "poi_name": "Premier Phường 3",
    "brand": "Premier",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Đà Lạt",
    "district": "Phường 3",
    "address": "136 Đường Trung Tâm, Phường 3",
    "latitude": 11.949474,
    "longitude": 108.4837,
    "rating": 4.0,
    "review_count": 1190,
    "popularity_score": 65.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "spa",
      "hồ bơi",
      "view đẹp",
      "phù hợp công tác"
    ],
    "tags": [
      "spa",
      "hồ-bơi",
      "view-đẹp",
      "phù-hợp-công-tác"
    ],
    "description": "Premier Phường 3 tại Phường 3, Đà Lạt, có các đặc điểm: spa, hồ bơi, view đẹp, phù hợp công tác.",
    "source_row": 101,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G062",
    "poi_name": "Golden Lotus Phường 4",
    "brand": "Golden Lotus",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Đà Lạt",
    "district": "Phường 4",
    "address": "33 Đường Trung Tâm, Phường 4",
    "latitude": 11.907657,
    "longitude": 108.472966,
    "rating": 4.6,
    "review_count": 2018,
    "popularity_score": 87.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "view đẹp",
      "phù hợp gia đình",
      "bữa sáng",
      "gần biển"
    ],
    "tags": [
      "view-đẹp",
      "phù-hợp-gia-đình",
      "bữa-sáng",
      "gần-biển"
    ],
    "description": "Golden Lotus Phường 4 tại Phường 4, Đà Lạt, có các đặc điểm: view đẹp, phù hợp gia đình, bữa sáng, gần biển.",
    "source_row": 102,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G063",
    "poi_name": "Mường Thanh Phường 1",
    "brand": "Mường Thanh",
    "category": "Khách sạn",
    "sub_category": "Hotel",
    "city": "Đà Lạt",
    "district": "Phường 1",
    "address": "115 Đường Trung Tâm, Phường 1",
    "latitude": 11.922793,
    "longitude": 108.430933,
    "rating": 3.9,
    "review_count": 2219,
    "popularity_score": 56.0,
    "price_level": 4,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "giá dưới 2 triệu",
      "view đẹp",
      "phù hợp công tác",
      "phù hợp gia đình"
    ],
    "tags": [
      "giá-dưới-2-triệu",
      "view-đẹp",
      "phù-hợp-công-tác",
      "phù-hợp-gia-đình"
    ],
    "description": "Mường Thanh Phường 1 tại Phường 1, Đà Lạt, có các đặc điểm: giá dưới 2 triệu, view đẹp, phù hợp công tác, phù hợp gia đình.",
    "source_row": 103,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G064",
    "poi_name": "ACB Phường 1",
    "brand": "ACB",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Đà Lạt",
    "district": "Phường 1",
    "address": "60 Đường Trung Tâm, Phường 1",
    "latitude": 11.945257,
    "longitude": 108.425931,
    "rating": 4.4,
    "review_count": 604,
    "popularity_score": 90.0,
    "price_level": 3,
    "opening_hours": "24/7",
    "attributes": [
      "24/7",
      "gần trung tâm",
      "rút tiền"
    ],
    "tags": [
      "24/7",
      "gần-trung-tâm",
      "rút-tiền"
    ],
    "description": "ACB Phường 1 tại Phường 1, Đà Lạt, có các đặc điểm: 24/7, gần trung tâm, rút tiền.",
    "source_row": 104,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G065",
    "poi_name": "VPBank Phường 8",
    "brand": "VPBank",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Đà Lạt",
    "district": "Phường 8",
    "address": "19 Đường Trung Tâm, Phường 8",
    "latitude": 11.926424,
    "longitude": 108.489348,
    "rating": 4.0,
    "review_count": 1148,
    "popularity_score": 64.0,
    "price_level": 1,
    "opening_hours": "24/7",
    "attributes": [
      "gần trung tâm",
      "24/7",
      "rút tiền"
    ],
    "tags": [
      "gần-trung-tâm",
      "24/7",
      "rút-tiền"
    ],
    "description": "VPBank Phường 8 tại Phường 8, Đà Lạt, có các đặc điểm: gần trung tâm, 24/7, rút tiền.",
    "source_row": 105,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G066",
    "poi_name": "ACB Phường 1",
    "brand": "ACB",
    "category": "ATM",
    "sub_category": "ATM",
    "city": "Đà Lạt",
    "district": "Phường 1",
    "address": "81 Đường Trung Tâm, Phường 1",
    "latitude": 11.95052,
    "longitude": 108.485164,
    "rating": 4.2,
    "review_count": 1041,
    "popularity_score": 85.0,
    "price_level": 2,
    "opening_hours": "24/7",
    "attributes": [
      "rút tiền",
      "gần trung tâm",
      "24/7"
    ],
    "tags": [
      "rút-tiền",
      "gần-trung-tâm",
      "24/7"
    ],
    "description": "ACB Phường 1 tại Phường 1, Đà Lạt, có các đặc điểm: rút tiền, gần trung tâm, 24/7.",
    "source_row": 106,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G067",
    "poi_name": "Trạm xăng Mipec Phường 1",
    "brand": "Mipec",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Đà Lạt",
    "district": "Phường 1",
    "address": "128 Đường Trung Tâm, Phường 1",
    "latitude": 11.967339,
    "longitude": 108.468602,
    "rating": 3.9,
    "review_count": 1013,
    "popularity_score": 92.0,
    "price_level": 4,
    "opening_hours": "24/7",
    "attributes": [
      "bơm lốp",
      "24/7",
      "cửa hàng tiện lợi",
      "toilet"
    ],
    "tags": [
      "bơm-lốp",
      "24/7",
      "cửa-hàng-tiện-lợi",
      "toilet"
    ],
    "description": "Trạm xăng Mipec Phường 1 tại Phường 1, Đà Lạt, có các đặc điểm: bơm lốp, 24/7, cửa hàng tiện lợi, toilet.",
    "source_row": 107,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G068",
    "poi_name": "Trạm xăng PVOIL Phường 3",
    "brand": "PVOIL",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Đà Lạt",
    "district": "Phường 3",
    "address": "93 Đường Trung Tâm, Phường 3",
    "latitude": 11.95318,
    "longitude": 108.437166,
    "rating": 4.5,
    "review_count": 3107,
    "popularity_score": 82.0,
    "price_level": 1,
    "opening_hours": "24/7",
    "attributes": [
      "cửa hàng tiện lợi",
      "24/7",
      "toilet",
      "bơm lốp"
    ],
    "tags": [
      "cửa-hàng-tiện-lợi",
      "24/7",
      "toilet",
      "bơm-lốp"
    ],
    "description": "Trạm xăng PVOIL Phường 3 tại Phường 3, Đà Lạt, có các đặc điểm: cửa hàng tiện lợi, 24/7, toilet, bơm lốp.",
    "source_row": 108,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G069",
    "poi_name": "Trạm xăng Mipec Phường 2",
    "brand": "Mipec",
    "category": "Trạm xăng",
    "sub_category": "Fuel Station",
    "city": "Đà Lạt",
    "district": "Phường 2",
    "address": "120 Đường Trung Tâm, Phường 2",
    "latitude": 11.920901,
    "longitude": 108.476533,
    "rating": 4.1,
    "review_count": 2634,
    "popularity_score": 81.0,
    "price_level": 2,
    "opening_hours": "24/7",
    "attributes": [
      "toilet",
      "cửa hàng tiện lợi",
      "24/7",
      "bơm lốp"
    ],
    "tags": [
      "toilet",
      "cửa-hàng-tiện-lợi",
      "24/7",
      "bơm-lốp"
    ],
    "description": "Trạm xăng Mipec Phường 2 tại Phường 2, Đà Lạt, có các đặc điểm: toilet, cửa hàng tiện lợi, 24/7, bơm lốp.",
    "source_row": 109,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G070",
    "poi_name": "GO! Phường 2",
    "brand": "GO!",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Đà Lạt",
    "district": "Phường 2",
    "address": "101 Đường Trung Tâm, Phường 2",
    "latitude": 11.909205,
    "longitude": 108.424954,
    "rating": 4.3,
    "review_count": 1781,
    "popularity_score": 53.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "bãi đỗ xe",
      "mua sắm",
      "rạp phim",
      "gia đình"
    ],
    "tags": [
      "bãi-đỗ-xe",
      "mua-sắm",
      "rạp-phim",
      "gia-đình"
    ],
    "description": "GO! Phường 2 tại Phường 2, Đà Lạt, có các đặc điểm: bãi đỗ xe, mua sắm, rạp phim, gia đình.",
    "source_row": 110,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G071",
    "poi_name": "GO! Phường 2",
    "brand": "GO!",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Đà Lạt",
    "district": "Phường 2",
    "address": "21 Đường Trung Tâm, Phường 2",
    "latitude": 11.970612,
    "longitude": 108.446347,
    "rating": 4.0,
    "review_count": 2229,
    "popularity_score": 79.0,
    "price_level": 1,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "bãi đỗ xe",
      "rạp phim",
      "gia đình",
      "mua sắm"
    ],
    "tags": [
      "bãi-đỗ-xe",
      "rạp-phim",
      "gia-đình",
      "mua-sắm"
    ],
    "description": "GO! Phường 2 tại Phường 2, Đà Lạt, có các đặc điểm: bãi đỗ xe, rạp phim, gia đình, mua sắm.",
    "source_row": 111,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  },
  {
    "poi_id": "G072",
    "poi_name": "GO! Phường 3",
    "brand": "GO!",
    "category": "Trung tâm thương mại",
    "sub_category": "Mall",
    "city": "Đà Lạt",
    "district": "Phường 3",
    "address": "28 Đường Trung Tâm, Phường 3",
    "latitude": 11.905601,
    "longitude": 108.442886,
    "rating": 4.1,
    "review_count": 586,
    "popularity_score": 85.0,
    "price_level": 2,
    "opening_hours": "07:00-22:00",
    "attributes": [
      "rạp phim",
      "gia đình",
      "ăn uống",
      "mua sắm"
    ],
    "tags": [
      "rạp-phim",
      "gia-đình",
      "ăn-uống",
      "mua-sắm"
    ],
    "description": "GO! Phường 3 tại Phường 3, Đà Lạt, có các đặc điểm: rạp phim, gia đình, ăn uống, mua sắm.",
    "source_row": 112,
    "provenance": "synthetic-p7-workbook:POI_Dataset"
  }
] as const;
